### ISSUE TITLE
Latest npm package is not working

### ISSUE THREAD

**Issue by sadashivm** [toddbluhm/env-cmd#115]
Hi @toddbluhm 
I'm using your npm package in react js application. it is not working properly
I used below steps:
1. Install package locally
   `npm i env-cmd`
2. In package.json looks like

    ![image](https://user-images.githubusercontent.com/10355473/73928258-cd334500-48f8-11ea-805a-2a5b9f5c02c1.png)

3. Created a **.env-cmdrc** file in the root directory and structure as

    ![image](https://user-images.githubusercontent.com/10355473/73928409-0c619600-48f9-11ea-868e-5606769a0f7d.png)

4. Finally updated scripts object in package.json file like

    ![image](https://user-images.githubusercontent.com/10355473/73928592-5d718a00-48f9-11ea-9aba-7e54ebd36cc1.png)

5. run the below commond
    `npm start`

6.  Got the below error

    ![image](https://user-images.githubusercontent.com/10355473/73928774-ac1f2400-48f9-11ea-90d6-e959cbbdbc3c.png)

Please let me know if I've missed out anything.

**Comment by pgprateekgarg2** [comment]
replace env-cmd with ./node_modules/.bin/env-cmd -f

**Comment by pgprateekgarg2** [comment]
Replace env-cmd with ./node_modules/.bin/env-cmd -f 
It will work fine then.

**Comment by toddbluhm** [comment]
You should use the following command in your package.json: `env-cmd -e dev react-scripts start`. Per the docs, in version `10.x` and higher, when using a `.rc` file the environment must be specified using the `-e` flag.

**Comment by nodabladam** [comment]
Note that this error can happen if your file is broken.  I think the latest version is swallowing the critical part of the error.  Previous version will give something like:
```
SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    ...
    at Object.getRCFileVars (\node_modules\env-cmd\dist\parse-rc-file.js:26:33)
Error: Unable to locate .rc file at default locations (./.env-cmdrc,./.env-cmdrc.js,./.env-cmdrc.json)
```

Current version only seems to show the "Unable to locate .rc file" part.

**Comment by alexolivas** [comment]
I have pretty much the same setup as the original poster, but am still getting the same error even when I provide the `-e` flag.
<img width="449" alt="Screen Shot 2020-02-14 at 11 54 01 AM" src="https://user-images.githubusercontent.com/1382523/74551165-b310ec80-4f20-11ea-9e42-204429425b63.png">


<img width="891" alt="Screen Shot 2020-02-14 at 11 53 15 AM" src="https://user-images.githubusercontent.com/1382523/74551104-97a5e180-4f20-11ea-842f-a82fc25a660c.png">

And an `.env-cmdrc` file that looks like this:
```
{
    "dev": {
        "REACT_APP_ENVIRONMENT": "development",
        "REACT_APP_API_URL": "https://some-dev.endpoint.io"
    },
    "stage": {
        "REACT_APP_ENVIRONMENT": "stage",
        "REACT_APP_API_URL": "https://some-stage.endpoint.io"
    },
    "production": {
        "REACT_APP_ENVIRONMENT": "production",
        "REACT_APP_API_URL": "https://some-prod.endpoint.io"
    }
}
```

**Comment by alexolivas** [comment]
I confirmed locally, that there is a bug on the latest version `10.1.0`. When I downgraded to the previous version `10.0.1` the same command above (`npm run start:stage`) worked.

**Comment by toddbluhm** [comment]
@alexolivas could you set up an example repo for this? My tests/example repos are showing .rc files working as expected, but I don't have/use `react-scripts` so perhaps something else is causing the issue. An example repo would really help me pin this issue down 😄

**Comment by sadashivm** [comment]
@toddbluhm ,
It is working fine if i add -e flag in package.json file and I can access variables only i add REACT_APP_ as prefix. See below
![image](https://user-images.githubusercontent.com/10355473/74731935-1f685480-526f-11ea-9354-191978f13c3c.png)



For nested object it is not working.
  
![image](https://user-images.githubusercontent.com/10355473/74731878-0069c280-526f-11ea-9f81-9f2079c04652.png)

And output come like,


![image](https://user-images.githubusercontent.com/10355473/74731744-ad900b00-526e-11ea-8ae0-32e4152ea912.png)

Any idea to fetch the nested objects value ? it is coming as [object object]

**Comment by toddbluhm** [comment]
@sadashivm That is correct behavior. 

`env-cmd` was not designed to support nested objects. I am curious as to why you want nested values for an environment variable? Environment variables are almost by definition supposed to be simple values (strings, numbers, booleans). How would nested objects even work? What would the expected behavior of the keys be?

If you want to create a nested object, you can stringify the object yourself like this.
```
{
  "development": {
     "REACT_APP_ENV1": "{ "REACT_APP_ENV2": "nested value 1", "REACT_APP_ENV3": "nested value 2" }",
     "REACT_APP_ENV4": "thank you"
  }
}
```

Then you will have to access the nested values like this:
```
const obj = JSON.parse(process.env.REACT_APP_ENV1)
console.log(obj.REACT_APP_ENV2) // prints "nested value 1"
console.log(obj.REACT_APP_ENV3) // prints "nested value 2"
```

However, if you're saying you want to be able to access the values like this:
```
process.env.REACT_APP_ENV1
process.env.REACT_APP_ENV2
process.env.REACT_APP_ENV3
process.env.REACT_APP_ENV4
```
then you would need to have those values at the top level of the .env file
```
{
  "development": {
     "REACT_APP_ENV1": "some value",
     "REACT_APP_ENV2": "nested value 1",
     "REACT_APP_ENV3": "nested value 2",
     "REACT_APP_ENV4": "thank you"
  }
}
```

At this time I do not plan on adding any advanced nesting features to this project. I certainly could be convinced otherwise, but it would have to be something already standardized and with reasonable/expected behavior. Currently, nesting can be implemented via the solution above without any changes to `env-cmd`

Hopefully, that helps answer your issue 😄

**Comment by sadashivm** [comment]
@toddbluhm ,
Thank you so much for response.

**Comment by matomesc** [comment]
I'm getting the same error with `env-cmd@10.1.0`. My command looks like:

```
env-cmd -f ./.env-cmdrc.js -e development node
```

**Comment by toddbluhm** [comment]
Closing due to inactivity
