### ISSUE TITLE
error: unknown option --silent

### ISSUE THREAD

**Issue by psech** [toddbluhm/env-cmd#221]
I am receiving `error: unknown option --silent` when running `npm run cy:run`

env-cmd: v9.01
Node: v10.4.1
npm: v6.1.0
shell: zsh

## package.js
```
"cy:prerun": "rm -rf ./tests/cypress/cypress/screenshots ./tests/cypress/cypress/videos",
"cy:run": "npm run cy:prerun && env-cmd -f ./.env.local --silent cypress run --project tests/cypress --spec tests/cypress/cypress/integration/*",
```

## Output ~/.npm/_logs/2020-12-21T08_42_57_014Z-debug.log
```
10 silly lifecycle @ansarada/platform-home-spa@0.0.0~cy:run: Args: [ '-c',
10 silly lifecycle   'npm run cy:prerun && env-cmd -f ./.env.local --silent cypress run --project tests/cypress --spec tests/cypress/cypress/integration/*' ]
11 silly lifecycle @ansarada/platform-home-spa@0.0.0~cy:run: Returned: code: 1  signal: null
12 info lifecycle @ansarada/platform-home-spa@0.0.0~cy:run: Failed to exec cy:run script
13 verbose stack Error: @ansarada/platform-home-spa@0.0.0 cy:run: `npm run cy:prerun && env-cmd -f ./.env.local --silent cypress run --project tests/cypress --spec tests/cypress/cypress/integration/*`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/przemek.sech/.nvm/versions/node/v10.4.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/przemek.sech/.nvm/versions/node/v10.4.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

**Comment by k-yle** [comment]
Hey, you're using env-cmd `v9`, however, the `--silent` option is only available in `v10.1` or newer. 

If you're still having issues in `v10.1`, feel free to re-open this issue
