### ISSUE TITLE
env-cmd fails on WSL2

### ISSUE THREAD

**Issue by jadbox** [toddbluhm/env-cmd#76]
env-cmd 9.0.3 
env: Windows 10 WSL2

``` 
env-cmd -f ./.env.staging my-build-script                             
Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:394:11)                                                                at Object.spawn (child_process.js:535:9)                                                                                
at Object.spawn (/home/jdunlap/n/lib/node_modules/env-cmd/node_modules/cross-spawn/index.js:12:24)                      at Object.<anonymous> (/home/jdunlap/n/lib/node_modules/env-cmd/dist/env-cmd.js:57:30)                                  
at Generator.next (<anonymous>)
    at fulfilled (/home/jdunlap/n/lib/node_modules/env-cmd/dist/env-cmd.js:4:58) {                                        errno: 'EPERM',                                                                                                         
code: 'EPERM',                                                                                                          
syscall: 'spawn'                                                                                                      
}
```

**Comment by jadbox** [comment]
^ I've filed a joint bug on WSL2 for the syscall. I'm not sure which system is at fault though.

**Comment by toddbluhm** [comment]
@jadbox Seems like this might be a windows/ubuntu bug related to https://github.com/microsoft/WSL/issues/4175? Were you ever able to resolve this issue?

**Comment by jadbox** [comment]
I had to leave wsl2 due to the bug... I'll give it another try over the weekend if I can!

**Comment by toddbluhm** [comment]
Let me know what you come up with, but I will probably close this issue out as it seems like it really has nothing to do with this project, just an issue with WSL in general.

**Comment by jadbox** [comment]
Closing this for now as I don't have time to set up the Windows env again to test. Hopefully there's a better way to diagnose problematic wsl PATH issues in the future (if that's the issue).
