### ISSUE TITLE
Error: Invalid .rc file path.

### ISSUE THREAD

**Issue by kushalmahajan** [toddbluhm/env-cmd#77]
Here's my file `.env-cmdrc`

```
{
  "development": {
    "REACT_APP_NODE_ENV": "development",
    "REACT_APP_API_URL": "/local",
    "PUBLIC_URL": "/"
  },
  "staging": {
    "REACT_APP_NODE_ENV": "staging",
    "REACT_APP_API_URL": "/stage",
    "PUBLIC_URL": "/"
  },
  "production": {
    "REACT_APP_NODE_ENV": "production",
    "REACT_APP_API_URL": "/prod",
    "PUBLIC_URL": "/"
  }
}
```

And here's my start script

```
 "start": "env-cmd -e development node scripts/start.js ",
```

It fails with error 

> Error: Invalid .rc file path.
>at Object.<anonymous> (/Users/xxx/.Trash/yyy/node_modules/env-cmd/dist/parse-rc-file.js:27:19)
    at Generator.throw (<anonymous>)
    at rejected (/Users/xxx/.Trash/yyy/node_modules/env-cmd/dist/parse-rc-file.js:5:65)

Same setup is being run in another project. Can't figure out why is this happening!

**Comment by kushalmahajan** [comment]
Happened due `zsh` shell holding onto old files of another project folder with same name.
