### ISSUE TITLE
trying to use .env-cmd.. getting error

### ISSUE THREAD

**Issue by ShanthaSiva** [toddbluhm/env-cmd#82]
I am trying to set env variable through terminal like, 
node node_modules/env-cmd -f ./async-env.js node index.js

getting below error.. Please assist
TypeError: util_1.promisify is not a function
    at Object.<anonymous> (/node_modules/env-cmd/dist/parse-rc-file.js:15:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous>/node_modules/env-cmd/dist/get-env-vars.js:11:25)
    at Module._compile (module.js:570:32)

**Comment by Akkuma** [comment]
It looks like to me you're running some very old version of node as it is complaining about no promisify support.

**Comment by toddbluhm** [comment]
That seems to be the issue. NodeJS's official `promisify` util was added in node `v8.0.0`. Documentation for that function can be found here: https://nodejs.org/api/util.html#util_util_promisify_original

This project has a minimum supported NodeJS version of `8.0.0`. As @Akkuma said, it seems like you are running on an unsupported NodeJS version `< 8.0.0`

**Comment by toddbluhm** [comment]
Closing due to inactive/no response from the original poster.
